name: Deploy Weather App

on:
  push:
    branches:[main]
  workflow_dispatch:

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure/pages@v5

      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: Weather App

      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4
